### ISSUE TITLE
midway官网怎么挂了，好几天了，等着干活

### ISSUE THREAD

**Issue by Tokiham** [czy88840616/czy88840616#2]

**Comment by czy88840616** [comment]
官网都是正常访问的，如果在 wifi/4g 下都无法访问，请提供所在的地区以及网络服务商。


issue 提到 midway 中，这里不会有消息监控。。

**Comment by Tokiham** [comment]
地区：福建厦门
网络服务商：中国移动

**Comment by czy88840616** [comment]
福建地区网络是展示成反诈信息了吧，这是运营商拦截的，我们也没什么办法。作为替代，可以使用 beta.midwayjs.org 进行访问。
