### ISSUE TITLE
是否会持续更新，不忘初心的迭代？

### ISSUE THREAD

**Issue by xyuwan** [czy88840616/czy88840616#4]
从egg转过来。目前定义主要服务端技术栈，不希望后面慢慢淡漠了，实在受不了eggjs代码先行文档滞后的做法。

**Comment by czy88840616** [comment]
🤔 这个无法承诺，都是尽最大努力去做，一般不涉及到生存问题都问题不大。

**Comment by xyuwan** [comment]
是你们团队在维护吗？还是你个人在维护？

**Comment by czy88840616** [comment]
名义上是团队，其实这么多年一直只有我😄
