### ISSUE TITLE
关于 midway/hsf-server

### ISSUE THREAD

**Issue by unclesmiley** [czy88840616/czy88840616#5]
group的基础镜像里面是通过 kill signal 做优雅下线的，但是我看 hsf-server 里是通过监听请求来结束的（估计参考 java 实现？），这个好像对不上

ps：大佬是撤了嘛。。

**Comment by czy88840616** [comment]
kill 是杀进程，除了进程退出之外，还需要额外感知 configserver 的下线，否则业务调用的时候会有影响。

**Comment by unclesmiley** [comment]
@czy88840616  好的👌，那这个 hsf offline 请求是谁发呢？我看基础镜像里的 nodejsctl 脚本没有，需要自己定制镜像嘛

**Comment by unclesmiley** [comment]
另外想加个 wx 可以嘛hh，走的有点突然没来得及

**Comment by czy88840616** [comment]
wx就是github名
